version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  publish:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run: npm publish
workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
